// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	httpa "net/http"
	"sync"

	"github.com/bborbe/http"
)

type HttpProxyErrorHandler struct {
	HandleErrorStub        func(httpa.ResponseWriter, *httpa.Request, error)
	handleErrorMutex       sync.RWMutex
	handleErrorArgsForCall []struct {
		arg1 httpa.ResponseWriter
		arg2 *httpa.Request
		arg3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HttpProxyErrorHandler) HandleError(arg1 httpa.ResponseWriter, arg2 *httpa.Request, arg3 error) {
	fake.handleErrorMutex.Lock()
	fake.handleErrorArgsForCall = append(fake.handleErrorArgsForCall, struct {
		arg1 httpa.ResponseWriter
		arg2 *httpa.Request
		arg3 error
	}{arg1, arg2, arg3})
	stub := fake.HandleErrorStub
	fake.recordInvocation("HandleError", []interface{}{arg1, arg2, arg3})
	fake.handleErrorMutex.Unlock()
	if stub != nil {
		fake.HandleErrorStub(arg1, arg2, arg3)
	}
}

func (fake *HttpProxyErrorHandler) HandleErrorCallCount() int {
	fake.handleErrorMutex.RLock()
	defer fake.handleErrorMutex.RUnlock()
	return len(fake.handleErrorArgsForCall)
}

func (fake *HttpProxyErrorHandler) HandleErrorCalls(stub func(httpa.ResponseWriter, *httpa.Request, error)) {
	fake.handleErrorMutex.Lock()
	defer fake.handleErrorMutex.Unlock()
	fake.HandleErrorStub = stub
}

func (fake *HttpProxyErrorHandler) HandleErrorArgsForCall(i int) (httpa.ResponseWriter, *httpa.Request, error) {
	fake.handleErrorMutex.RLock()
	defer fake.handleErrorMutex.RUnlock()
	argsForCall := fake.handleErrorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *HttpProxyErrorHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HttpProxyErrorHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ http.ProxyErrorHandler = new(HttpProxyErrorHandler)
