// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	httpa "net/http"
	"sync"

	"github.com/bborbe/http"
	"github.com/bborbe/kv"
)

type HttpWithErrorTx struct {
	ServeHTTPStub        func(context.Context, kv.Tx, httpa.ResponseWriter, *httpa.Request) error
	serveHTTPMutex       sync.RWMutex
	serveHTTPArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 httpa.ResponseWriter
		arg4 *httpa.Request
	}
	serveHTTPReturns struct {
		result1 error
	}
	serveHTTPReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HttpWithErrorTx) ServeHTTP(arg1 context.Context, arg2 kv.Tx, arg3 httpa.ResponseWriter, arg4 *httpa.Request) error {
	fake.serveHTTPMutex.Lock()
	ret, specificReturn := fake.serveHTTPReturnsOnCall[len(fake.serveHTTPArgsForCall)]
	fake.serveHTTPArgsForCall = append(fake.serveHTTPArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 httpa.ResponseWriter
		arg4 *httpa.Request
	}{arg1, arg2, arg3, arg4})
	stub := fake.ServeHTTPStub
	fakeReturns := fake.serveHTTPReturns
	fake.recordInvocation("ServeHTTP", []interface{}{arg1, arg2, arg3, arg4})
	fake.serveHTTPMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *HttpWithErrorTx) ServeHTTPCallCount() int {
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	return len(fake.serveHTTPArgsForCall)
}

func (fake *HttpWithErrorTx) ServeHTTPCalls(stub func(context.Context, kv.Tx, httpa.ResponseWriter, *httpa.Request) error) {
	fake.serveHTTPMutex.Lock()
	defer fake.serveHTTPMutex.Unlock()
	fake.ServeHTTPStub = stub
}

func (fake *HttpWithErrorTx) ServeHTTPArgsForCall(i int) (context.Context, kv.Tx, httpa.ResponseWriter, *httpa.Request) {
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	argsForCall := fake.serveHTTPArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *HttpWithErrorTx) ServeHTTPReturns(result1 error) {
	fake.serveHTTPMutex.Lock()
	defer fake.serveHTTPMutex.Unlock()
	fake.ServeHTTPStub = nil
	fake.serveHTTPReturns = struct {
		result1 error
	}{result1}
}

func (fake *HttpWithErrorTx) ServeHTTPReturnsOnCall(i int, result1 error) {
	fake.serveHTTPMutex.Lock()
	defer fake.serveHTTPMutex.Unlock()
	fake.ServeHTTPStub = nil
	if fake.serveHTTPReturnsOnCall == nil {
		fake.serveHTTPReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.serveHTTPReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *HttpWithErrorTx) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HttpWithErrorTx) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ http.WithErrorTx = new(HttpWithErrorTx)
