// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	httpa "net/http"
	"sync"

	"github.com/bborbe/http"
)

type HttpWithError struct {
	ServeHTTPStub        func(context.Context, httpa.ResponseWriter, *httpa.Request) error
	serveHTTPMutex       sync.RWMutex
	serveHTTPArgsForCall []struct {
		arg1 context.Context
		arg2 httpa.ResponseWriter
		arg3 *httpa.Request
	}
	serveHTTPReturns struct {
		result1 error
	}
	serveHTTPReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HttpWithError) ServeHTTP(arg1 context.Context, arg2 httpa.ResponseWriter, arg3 *httpa.Request) error {
	fake.serveHTTPMutex.Lock()
	ret, specificReturn := fake.serveHTTPReturnsOnCall[len(fake.serveHTTPArgsForCall)]
	fake.serveHTTPArgsForCall = append(fake.serveHTTPArgsForCall, struct {
		arg1 context.Context
		arg2 httpa.ResponseWriter
		arg3 *httpa.Request
	}{arg1, arg2, arg3})
	stub := fake.ServeHTTPStub
	fakeReturns := fake.serveHTTPReturns
	fake.recordInvocation("ServeHTTP", []interface{}{arg1, arg2, arg3})
	fake.serveHTTPMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *HttpWithError) ServeHTTPCallCount() int {
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	return len(fake.serveHTTPArgsForCall)
}

func (fake *HttpWithError) ServeHTTPCalls(stub func(context.Context, httpa.ResponseWriter, *httpa.Request) error) {
	fake.serveHTTPMutex.Lock()
	defer fake.serveHTTPMutex.Unlock()
	fake.ServeHTTPStub = stub
}

func (fake *HttpWithError) ServeHTTPArgsForCall(i int) (context.Context, httpa.ResponseWriter, *httpa.Request) {
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	argsForCall := fake.serveHTTPArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *HttpWithError) ServeHTTPReturns(result1 error) {
	fake.serveHTTPMutex.Lock()
	defer fake.serveHTTPMutex.Unlock()
	fake.ServeHTTPStub = nil
	fake.serveHTTPReturns = struct {
		result1 error
	}{result1}
}

func (fake *HttpWithError) ServeHTTPReturnsOnCall(i int, result1 error) {
	fake.serveHTTPMutex.Lock()
	defer fake.serveHTTPMutex.Unlock()
	fake.ServeHTTPStub = nil
	if fake.serveHTTPReturnsOnCall == nil {
		fake.serveHTTPReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.serveHTTPReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *HttpWithError) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HttpWithError) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ http.WithError = new(HttpWithError)
